/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundCanvas: typeof import('./src/components/atoms/BackgroundCanvas.vue')['default']
    BaseAvatar: typeof import('./src/components/atoms/BaseAvatar.vue')['default']
    ChatComposer: typeof import('./src/components/molecules/ChatComposer.vue')['default']
    ChatLayoutTemplate: typeof import('./src/components/templates/ChatLayoutTemplate.vue')['default']
    ChatMembersRail: typeof import('./src/components/organisms/ChatMembersRail.vue')['default']
    ChatSidebar: typeof import('./src/components/organisms/ChatSidebar.vue')['default']
    ChatThread: typeof import('./src/components/organisms/ChatThread.vue')['default']
    ConversationItem: typeof import('./src/components/molecules/ConversationItem.vue')['default']
    CreateConversationPanel: typeof import('./src/components/organisms/CreateConversationPanel.vue')['default']
    DateDivider: typeof import('./src/components/molecules/DateDivider.vue')['default']
    ForwardConversationPicker: typeof import('./src/components/molecules/ForwardConversationPicker.vue')['default']
    IconGhostButton: typeof import('./src/components/atoms/IconGhostButton.vue')['default']
    LoadingText: typeof import('./src/components/atoms/LoadingText.vue')['default']
    MenuItemButton: typeof import('./src/components/atoms/MenuItemButton.vue')['default']
    MessageBubble: typeof import('./src/components/molecules/MessageBubble.vue')['default']
    MessageForwardQuote: typeof import('./src/components/molecules/MessageForwardQuote.vue')['default']
    MessageOptionsMenu: typeof import('./src/components/molecules/MessageOptionsMenu.vue')['default']
    MessageReplyQuote: typeof import('./src/components/molecules/MessageReplyQuote.vue')['default']
    MessageSeenByAvatars: typeof import('./src/components/molecules/MessageSeenByAvatars.vue')['default']
    MessageStatusBadge: typeof import('./src/components/atoms/MessageStatusBadge.vue')['default']
    ReplyPreviewBanner: typeof import('./src/components/molecules/ReplyPreviewBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemMessageText: typeof import('./src/components/atoms/SystemMessageText.vue')['default']
    TypingIndicator: typeof import('./src/components/molecules/TypingIndicator.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_b35c0eb9f9ee15bbe258e43f7d66f5ae/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_b35c0eb9f9ee15bbe258e43f7d66f5ae/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_b35c0eb9f9ee15bbe258e43f7d66f5ae/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_b35c0eb9f9ee15bbe258e43f7d66f5ae/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_b35c0eb9f9ee15bbe258e43f7d66f5ae/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap_b35c0eb9f9ee15bbe258e43f7d66f5ae/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UserPickerItem: typeof import('./src/components/molecules/UserPickerItem.vue')['default']
  }
}
