/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountChip: typeof import('./src/components/molecules/AccountChip.vue')['default']
    BaseAvatar: typeof import('./src/components/atoms/BaseAvatar.vue')['default']
    ChatComposer: typeof import('./src/components/molecules/ChatComposer.vue')['default']
    ChatLayoutTemplate: typeof import('./src/components/templates/ChatLayoutTemplate.vue')['default']
    ChatMembersRail: typeof import('./src/components/organisms/ChatMembersRail.vue')['default']
    ChatSidebar: typeof import('./src/components/organisms/ChatSidebar.vue')['default']
    ChatThread: typeof import('./src/components/organisms/ChatThread.vue')['default']
    ConversationItem: typeof import('./src/components/molecules/ConversationItem.vue')['default']
    CreateConversationPanel: typeof import('./src/components/organisms/CreateConversationPanel.vue')['default']
    DateDivider: typeof import('./src/components/molecules/DateDivider.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconGhostButton: typeof import('./src/components/atoms/IconGhostButton.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MessageBubble: typeof import('./src/components/molecules/MessageBubble.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._o5yodohb6lhsbw7uqwia5mrbci/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._o5yodohb6lhsbw7uqwia5mrbci/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._o5yodohb6lhsbw7uqwia5mrbci/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._o5yodohb6lhsbw7uqwia5mrbci/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._o5yodohb6lhsbw7uqwia5mrbci/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.5.0_@tiptap+extensions@3.20.0_@tiptap+core@3.20.0_@tiptap+pm@3.20.0__@tiptap+pm@3._o5yodohb6lhsbw7uqwia5mrbci/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UserPickerItem: typeof import('./src/components/molecules/UserPickerItem.vue')['default']
  }
}
